apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection
  labels:
    app: object-detection
spec:
  selector:
    matchLabels:
      app: object-detection
  replicas: 3
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: kpan0021/object-detection-service
        ports:
        - containerPort: 5000
        resources:
          limits:
           cpu: "0.5"
          requests:
           cpu: "0.5"
